//! Experimental inference engine constants and benchmark defaults.

/// Default maximum tokens generated by a benchmark iteration.
pub const BENCH_DEFAULT_MAX_TOKENS: usize = 128;

/// Default number of benchmark iterations per engine.
pub const BENCH_DEFAULT_ITERATIONS: usize = 3;

/// Default prompt used when the user does not supply one.
pub const BENCH_DEFAULT_PROMPT: &str =
    "Write a short Rust function that computes the nth Fibonacci number. Return only code.";

/// Default device purchase price in USD used for amortization math.
///
/// Jetson Orin NX Super developer kit pricing varies; 699 USD is a reasonable
/// mid-range assumption for the full dev kit (module + carrier + power supply).
pub const BENCH_DEFAULT_DEVICE_COST_USD: f64 = 699.0;

/// Default electricity price in USD per kWh.
pub const BENCH_DEFAULT_ELECTRICITY_USD_PER_KWH: f64 = 0.15;

/// Assumed device lifetime in years for hardware amortization.
pub const BENCH_DEVICE_LIFETIME_YEARS: f64 = 5.0;

/// Assumed fraction of a day the device runs inference (duty cycle).
pub const BENCH_DEVICE_DUTY_CYCLE: f64 = 0.5;

/// Approximate characters per token for estimating token counts when an engine
/// does not report its own counts (matching the TUI's existing heuristic).
pub const CHARS_PER_TOKEN: f64 = 4.0;

/// Candidate `trtexec` executable paths, searched in order.
pub const TRTEXEC_CANDIDATES: &[&str] = &[
    "/usr/src/tensorrt/bin/trtexec",
    "/opt/tensorrt/bin/trtexec",
    "/usr/local/bin/trtexec",
    "trtexec",
];

/// Default TensorRT input sequence length used to convert inferences/sec into
/// a prefill-only tokens/sec figure.
pub const TRTEXEC_DEFAULT_SEQ_LEN: usize = 128;

/// Default number of trtexec repetitions for stable latency numbers.
pub const TRTEXEC_DEFAULT_AVG_RUNS: usize = 20;

/// Default trtexec warm-up duration in milliseconds.
pub const TRTEXEC_DEFAULT_WARMUP_MILLIS: usize = 500;

/// vLLM is intentionally not part of this branch; the reason is documented.
pub const VLLM_NOT_AVAILABLE_REASON: &str =
    "vLLM does not provide official aarch64/Jetson wheels and is not viable on Orin-class unified memory today.";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn benchmark_defaults_are_positive() {
        const _: () = {
            assert!(BENCH_DEFAULT_MAX_TOKENS > 0);
            assert!(BENCH_DEFAULT_ITERATIONS > 0);
            assert!(BENCH_DEFAULT_DEVICE_COST_USD > 0.0);
            assert!(BENCH_DEFAULT_ELECTRICITY_USD_PER_KWH > 0.0);
            assert!(TRTEXEC_DEFAULT_SEQ_LEN > 0);
        };
    }
}
